# Generated by Django 5.1 on 2024-08-13 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(verbose_name='Номер игры')),
                ('status', models.CharField(choices=[('win', 'Победа'), ('loose', 'Поражение'), ('in_proccess', 'В процессе')], max_length=20, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата игры')),
                ('players', models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Игроки')),
            ],
        ),
    ]
