# Generated by Django 5.1 on 2024-08-18 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.AddField(
            model_name='game',
            name='match_id',
            field=models.IntegerField(default=10, verbose_name='Идентификатор игры'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(editable=False, help_text='Получена от GSI', verbose_name='Информация')),
                ('game', models.ForeignKey(help_text='Игра, к которой относится данная информация', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='games.game', verbose_name='Игра')),
                ('player', models.ForeignKey(help_text='Игрок, к которому относится данная информация', on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Строка данных игры',
                'verbose_name_plural': 'Данные игры',
            },
        ),
    ]
