# Generated by Django 5.1 on 2024-08-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_date_game_datetime_gamedata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='data',
            field=models.JSONField(help_text='Получена от GSI', verbose_name='Информация'),
        ),
    ]
