# Generated by Django 5.1 on 2024-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gamedata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='datetime',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='timestamp',
            field=models.IntegerField(default=999999999, help_text='Когда была сформирована данная информация от GSI', verbose_name='Временная метка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания игры в БД', verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='match_id',
            field=models.IntegerField(help_text='ID игры, присвоенный Dota', verbose_name='Идентификатор игры'),
        ),
    ]
