# Generated by Django 5.1 on 2024-09-04 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_gamedata_datetime_gamedata_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='win_team',
            field=models.CharField(blank=True, choices=[('dire', 'Dire'), ('radiant', 'Radiant')], max_length=10, null=True, verbose_name='Команда победителя'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('dire', 'Dire'), ('radiant', 'Radiant')], max_length=10, verbose_name='Команда')),
                ('hero', models.CharField(max_length=100, verbose_name='Герой')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='player',
            field=models.ForeignKey(help_text='Игрок, к которому относится данная информация', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='games.player', verbose_name='Игрок'),
        ),
    ]
