# Generated by Django 5.1 on 2024-09-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_gamedata_options_remove_gamedata_clock_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='clock_time',
            field=models.IntegerField(default=0, help_text='Время в секундах', verbose_name='Время'),
            preserve_default=False,
        ),
    ]
