# Generated by Django 5.1 on 2024-08-13 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16, unique=True, verbose_name='Значение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gsi_token', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'GSI Токен',
                'verbose_name_plural': 'GSI Токены',
            },
        ),
    ]
